### ISSUE TITLE
[FEAT]: ProductCard, ProductPage

### ISSUE THREAD

**Issue by Maubry94** [mathcovax/mon-enorme-tronc#107]
ProductCard :
- [x] Normaliser la taille
- [x] Mettre le prix en bas à droite

ProductPage :
- [x] Ajouter les nouvelles caractéristiques des produits ()

**Comment by mathcovax** [comment]
- [x] mettre une vérification du nombre de produits dans la panier a max 10
- [x] mettre une vérification sur la quantité dans produits a max 15
- [x] soustraire au produit disponible le nombre déjà dans le panier
