### ISSUE TITLE
[FEAT]: Dashboard stat par organisation

### ISSUE THREAD

**Issue by ZeRiix** [mathcovax/mon-enorme-tronc#110]
- [x] créer une collection de données dénormalisées contenant tous les champs nécéssaire à la construction de toutes stats de tout les combinaisons de widget possible. (⚠️ calculer uniquement les données des widgets contenu dans la grid de stats)
- [x] Créer un script `indexingData.ts` dans le dossier `duplo/src/script` qui dénormalise les données de postgres vers la collection mongo
- [x] Ajouter une commande dans le package.json `indexiung:stat` (ajouter également dans le package global)
- [x] Créer une route PATCH pour modifier la grid d'une organization
- [x] Créer une route GET pour récupérer la grid
- [ ] Créer un queryBuilder mongoose pour récuperer les data pour les widget
- [ ] Créer une route GET pour récuperer les données d'un widgets
- [ ] construire les widgets en utilisant la [lib](https://www.shadcn-vue.com/docs/charts)
- [ ] Créer un form dynamique dans une `ThePopup` pour edit et add des widgets
- [ ] Ajouter un hook qui mes à jour les données indexer (status)

 ⚠️  Il faut impérativement que ca corresponde au attente du sujet) ⚠️ 
#### USER STORY:

- Je voudrais pouvoir customiser mon dashboard en choisissant le type de graphique/affichage de la données mais aussi la données sélectionnées.
- Je veux que le dashboard soit agencer avec des widgets ou je peux choisir la position de chacun d'entre eux.

**Comment by Maubry94** [comment]
Je pense qu'on va plutôt utiliser [celle-là](https://grid-layout-plus.netlify.app/example/basic.html) pour les grids (quasi pareille).
