### ISSUE TITLE
[FEAT]: Category and produt pages

### ISSUE THREAD

**Issue by ZeRiix** [mathcovax/mon-enorme-tronc#92]
- [x] Créer une page `CategoriesPage` dans le domain `product`
- [x] Créer la page `CategoryPage.vue` dans le domaine `product`
- [x] Créer la page `ProductPage.vue` dans le domain `product`
- [ ] Créer le composant `TheRange.vue` et l'ajouter aux composants globaux
- [x] Créer le composant `TheQuantity` et l'ajouter au composants globaux
- [ ] Créer l'élément de recherche avec les filtres (faire quelque chose similaire à la vue filter sur ma maquette figma
    - Créer une route GET `/filters`
    - Effectuer un foreach sur pour construire les filtres

_Note : partir de la branche de @mathcovax feat(91)_

**Comment by Maubry94** [comment]
Je m'occupe de la page des produits. A moins que tu ne l'aies déjà commencé @Vitaalx ?

**Comment by Vitaalx** [comment]
A cas où @Maubry94, je m'occupe du back.
