### ISSUE TITLE
[FEAT] page panier

### ISSUE THREAD

**Issue by mathcovax** [mathcovax/mon-enorme-tronc#99]
- [x] créer l'entité `article` avec les props suivantes: 
  - id
  - user
  - productSheet
  - createdAt
- [x] créer un service `ProductAvailability` avec une method `quantity` renvois la quantité de produit disponible pour une fiche produit.
- [x] créer la route api POST `/user/article`
  - vérifier en amont la disponibilité du produit
- [x] créer la route api DELETE `/article/{productSheetId}` (supprimer le premier correspondent)
- [x] créer la route api GET `/cart` (qui renvois le document panier).
- [x] créer la page panier en front dans le domain self
- [ ] faire en sorte qu'on puise ajouter au "panier" un produit

**Comment by Maubry94** [comment]
La page panier avait déjà été commencée (voir [CartPage.vue](https://github.com/mathcovax/mon-enorme-tronc/blob/develop/vue/src/domains/user/pages/CartPage.vue)).
